controller_manager:
  ros__parameters:
    update_rate: 50 #Hz
    rotation_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    wheel_controller:
      type: diff_drive_controller/DiffDriveController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
rotation_controller:
  ros__parameters:
    joints:
      - q1
      - q2 #проскальзывающее колесо(хорошо бы было чтобы оно было ориентировано по траектории робота)
      - q3
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true

wheel_controller:
  ros__parameters:
    left_wheel_names: ["q10"]
    right_wheel_names: ["q11"]
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    wheel_separation: 0.33072
    wheels_per_side: 1
    wheel_radius: 0.025
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0